// Emits USAGE_MONITORING.md from the same definitions the model is built from,
// so the documented measure list can never drift from the shipped model.
const fs = require('fs');
const path = require('path');
const { TABLES, ENVS, REPO } = require('./gen-usage.js');
const { BRAND } = require('./theme.js');
// pages.js is a factory. Render it with the SHIPPED feature set so the page and
// visual counts below match what is actually in the project, rather than
// including the pages and buttons that are currently switched off.
const SHIPPED = ['theme', 'vstyles', 'hier', 'chrome', 'pagenav'];
const PAGES = require('./pages.js')(
  s => require('crypto').createHash('sha1').update('uid|' + s).digest('hex').slice(0, 20),
  BRAND, ENVS.dev, f => SHIPPED.includes(f));

const L = [];
L.push('# Usage_Monitoring');
L.push('');
L.push('A Snowflake platform-telemetry report over `MONITORING_DB`, built once and');
L.push('shipped to both environments. The two copies are byte-identical apart from');
L.push('`expressions.tmdl`:');
L.push('');
L.push('| | dev_reports | prod_reports |');
L.push('|---|---|---|');
L.push(`| Server | \`${ENVS.dev.server}\` | \`${ENVS.prod.server}\` |`);
L.push(`| Warehouse | \`${ENVS.dev.warehouse}\` | \`${ENVS.prod.warehouse}\` |`);
L.push(`| Role | \`${ENVS.dev.role}\` | \`${ENVS.prod.role}\` |`);
L.push(`| Database | \`${ENVS.dev.database}\` | \`${ENVS.prod.database}\` |`);
L.push('| Account | `ZN91934` | `TG52301` |');
L.push('');
L.push('Storage mode is **Import**, not DirectQuery. The whole model is well under a');
L.push('million rows, and Import buys full DAX, time intelligence and instant visuals.');
L.push('That is the opposite call from the GOLD model next door, where a 305M-row table');
L.push('forced DirectQuery.');
L.push('');
L.push('## Known gaps in the source data');
L.push('');
L.push('These are properties of the source, not of the report. Visuals bound to them');
L.push('render empty until the platform team populates them.');
L.push('');
L.push('| Source | dev | prod | Effect |');
L.push('|---|---|---|---|');
L.push('| `GOLD_DTS_REFRESH_LONG_TERM_HISTORY` | 3,689 rows | **0** | Pipeline Health shows SILVER only in prod |');
L.push('| `VW_GOLD_TABLE_CURRENT/HISTORY_COUNT` | 31 / 2,402 | **0 / 0** | No GOLD layer in prod inventory or growth |');
L.push('| `*_DTS_REFRESH_SHORT_TERM_HISTORY` | **0** | **0** | Not used by the model at all |');
L.push('| `TALEND.TALEND_LOGS` / `TALEND_STATISTICS` | **0** | **0** | No Talend analytics possible yet |');
L.push('| `CDC` schema | no objects | no objects | No CDC analytics possible yet |');
L.push('');
L.push('`ARABIANSHIELD_PROD` has only BRONZE and SILVER today - there is no GOLD schema -');
L.push('which is why prod GOLD telemetry is empty rather than broken.');
L.push('');
L.push('`SNOWFLAKE.ACCOUNT_USAGE` is **not** granted to either reader role, so richer');
L.push('telemetry (query history, login history, storage growth) is out of reach unless');
L.push('the platform team exposes it as another view in `MONITORING_DB`.');
L.push('');
L.push('## Branding');
L.push('');
L.push('The Arabian Shield palette was taken from the live site (der3.com) by reading');
L.push('its computed styles rather than eyeballing a screenshot:');
L.push('');
L.push('| Role | Hex | Where it comes from |');
L.push('|---|---|---|');
L.push('| Primary green | `#00602F` | nav bar / "Contact us" button |');
L.push('| Accent lime | `#81A53F` | "Get a quote" button |');
L.push('| Deep greens | `#1F6035` `#146032` | secondary surfaces |');
L.push('| Ink | `#1D1D1B` | body text |');
L.push('');
L.push('It ships as the report **base theme**');
L.push('(`StaticResources/SharedResources/BaseThemes/ArabianShield.json`), not as a');
L.push('`customTheme`. That matters: registering it as a customTheme - tried under both');
L.push('`SharedResources` and `RegisteredResources` - makes Power BI reject the whole');
L.push('report layer. Every page vanishes while the semantic model still loads fine, so');
L.push('the TMDL validator reports OK and the failure looks like a data problem.');
L.push('');
L.push('Only the first two categorical slots are brand greens. Series three onward move');
L.push('to complementary hues, because four shades of green in one chart is unreadable.');
L.push('');
L.push('## Report features');
L.push('');
L.push('Each was verified in Desktop individually - see `UM_FEATURES` in');
L.push('`tools/usage-monitoring/build-usage.js`.');
L.push('');
L.push('| Feature | State | Note |');
L.push('|---|---|---|');
L.push('| `theme` + `vstyles` | **on** | brand palette, green table headers, styled slicers and titles |');
L.push('| `hier` | **on** | drill-down hierarchies: Layer → Schema → Table, Year → Month → Date |');
L.push('| `chrome` | **on** | brand header band and page title |');
L.push('| slicers | **on** | Date (range), Layer, Month on every page |');
L.push('| `pagenav` | **on** | built-in pageNavigator: one labelled button per page, current page highlighted |');
L.push('| `nav` | **off** | hand-rolled `actionButton`s rendered as unlabelled boxes - the `text` object is never applied, even with an explicit `default` state selector. `pagenav` replaces them. |');
L.push('| `tips` | **off** | report-page tooltips and the drillthrough detail page. The `pageBinding` shape for Tooltip/Drillthrough pages is wrong somewhere and takes the whole report layer down with it. Default hover tooltips still work. |');
L.push('');
L.push('Both `nav` and `tips` are one flag away once the correct JSON shape is known;');
L.push('the pages and buttons are already written in `pages.js`.');
L.push('');
L.push('## Tables');
L.push('');
L.push('| Table | Source | Rows (dev / prod) |');
L.push('|---|---|---|');
L.push('| `DTS_Refresh` | GOLD + SILVER refresh history, unioned with a `LAYER` tag | 30,344 / 372,284 |');
L.push('| `Table_Snapshots` | `TABLE_COUNT_DAILY_SNAPSHOTS` | 46,537 / 19,179 |');
L.push('| `Current_Tables` | 3 layer `*_CURRENT_COUNT` views, unioned | 607 / 519 |');
L.push('| `Daily_Consumption` | `VW_DAILY_CONSUMPTION_SUMMARY` | 121 / 45 |');
L.push('| `Hourly_Consumption` | `VW_VWH_HOURLY_CONSUMPTION_7D` | 69 / 349 |');
L.push('| `Date` | DAX calculated, spans whatever the facts contain | - |');
L.push('');
L.push('`Date` is a single conformed dimension joined 1-to-many to all four dated facts,');
L.push('so one date slicer drives every page.');
L.push('');
L.push('## Pages');
L.push('');
PAGES.forEach(p => L.push(`- **${p.name}** - ${p.visuals.length} visuals`));
L.push('');
L.push('## Measures');
L.push('');
let total = 0;
TABLES.forEach(t => {
  if (!t.measures || !t.measures.length) return;
  total += t.measures.length;
  L.push(`### \`${t.name}\``);
  L.push('');
  L.push('| Measure | DAX | Notes |');
  L.push('|---|---|---|');
  t.measures.forEach(([n, dax, , doc]) => {
    L.push(`| **${n}** | \`${dax.replace(/\|/g, '\\|')}\` | ${doc || ''} |`);
  });
  L.push('');
});
L.push(`_${total} measures._`);
L.push('');
L.push('### Semi-additive handling');
L.push('');
L.push('`Table_Snapshots` is a daily snapshot: summing `ROW_COUNT` across dates counts');
L.push('the same table once per day and is meaningless. `Rows (Snapshot)` is the plain');
L.push('sum, correct only with a single date in context. `Rows (Latest)` wraps it in');
L.push('`LASTNONBLANK` so totals and cards report the most recent snapshot instead.');
L.push('Use `(Latest)` for KPIs and `(Snapshot)` for trends over a date axis.');
L.push('');
L.push('## Regenerating');
L.push('');
L.push('Both copies are emitted from one definition. Editing either project by hand');
L.push('will be overwritten on the next generation - change the generator instead, or');
L.push('stop generating and own the files.');
L.push('');
L.push('Validate after any hand-edit:');
L.push('');
L.push('```powershell');
L.push('.\\tools\\Validate-Tmdl.ps1 -DefinitionPath ".\\dev_reports\\Usage_Monitoring.SemanticModel\\definition"');
L.push('```');
L.push('');
L.push('## First open');
L.push('');
L.push('Credentials are never stored in the project files. On first open Power BI will');
L.push('prompt: choose **Key-Pair**, then');
L.push('');
L.push('| | dev | prod |');
L.push('|---|---|---|');
L.push('| User | `SVC_QLIK_DEV` | `SVC_QLIK_PROD` |');
L.push('| Key file | `Dev_Credintials/qlik_dev_key_unencrypted.p8` | `Prod_Credintials/qlik_prod_key_unencrypted.p8` |');
L.push('| Passphrase | *(blank)* | *(blank)* |');
L.push('');
L.push('Use the `_unencrypted` keys. The `BEGIN ENCRYPTED PRIVATE KEY` variants carry an');
L.push('empty passphrase, which the ADBC driver rejects with');
L.push('`jwt_private_key_pkcs8_password is not configured`.');
fs.writeFileSync(path.join(REPO, 'USAGE_MONITORING.md'), L.join('\r\n') + '\r\n', 'utf8');
console.log(`wrote USAGE_MONITORING.md  (${total} measures, ${PAGES.length} pages)`);
